services:
  - type: web
    name: footwear-wearable-dashboard
    runtime: python
    buildCommand: pip install --no-cache-dir -r requirements.txt
    startCommand: bash -c "source .venv/bin/activate && gunicorn app:server"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.10